global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # Scrape metrics from Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from your Spring Boot REST service
  - job_name: 'rest-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
